// Repair prompts retain full diagnostics for the model. Display copy is
// separate so automated requests don't fill the chat with paths and errors.
export const AUTO_FIX_PROMPT = 'Automatically fixing a problem';
export const AUTO_FIX_REPLY = 'An automatic fix has been applied.';
export const AUTO_FIX_FAILURE = 'The automatic fix could not be completed. Try asking for a change or restoring an earlier version.';

export function isAutomaticRepair(entry) {
  if (typeof entry?.isAutoFix === 'boolean') return entry.isAutoFix;
  // Older versions and interrupted jobs predate the explicit flag. Match
  // only the specific request formats generated by App's repair handlers.
  return /^Fix these JavaScript syntax errors in the app code:\n|^Fix this runtime error(?: on the page [^\n]+| in the preview(?: \(on the [^\n]+ route\))?)?:\n/.test(entry?.prompt || '');
}

export const displayBuildPrompt = (entry) => isAutomaticRepair(entry) ? AUTO_FIX_PROMPT : entry?.prompt;
export const displayBuildReply = (entry) => entry?.reply && isAutomaticRepair(entry) ? AUTO_FIX_REPLY : entry?.reply;

export const automaticRepairStatus = (status) => /check|verif|review|inspect|read|search|look|list/i.test(status || '')
  ? 'Checking for problems…'
  : 'Applying an automatic fix…';
